# Generated by Django 5.2.7 on 2025-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField(default=False)),
                ('is_natural', models.BooleanField(default=False)),
                ('vowels', models.IntegerField(default=0)),
                ('consonants', models.IntegerField(default=0)),
            ],
        ),
    ]
